on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited, deleted]

name: Guestbook

permissions:
  contents: write        # allows pushing commits
  issues: read           # allows reading issue titles and comments

jobs:
  update_guestbook:
    name: Update guestbook
    if: ${{ github.event.issue.title == 'Guestbook 📖' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Update guestbook from comments
        uses: actions/github-script@v7
        with:
          script: |
            const guestbook = require('./guestbook.js')
            guestbook({ github, context })

      - name: Commit and push guestbook update
        run: |
          git config --global user.name 'anshumanjadiya1102'
          git config --global user.email 'anshumanjadiya1102@users.noreply.github.com'
          git add README.md
          git commit -m 'feat: update guestbook in README' || echo "No changes to commit"
          git push
